export const userActionTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    SET_USER_ACTIVE: 'SET_USER_ACTIVE',
    SET_ISLOADING:'SET_ISLOADING',
    SET_USER_PHONE:'SET_USER_PHONE',
    SET_USER_PROFILE_DATA:'SET_USER_PROFILE_DATA',
    
}